name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-addon:
    name: Package addon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Package addon (GDScript)
        run: |
          mkdir -p package/addons
          cp -r addons/Gedis package/addons/
          cd package
          zip -r ../gedis.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gedis
          path: gedis.zip

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-addon]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release package
        run: |
          mkdir -p release_package
          unzip artifacts/gedis/gedis.zip -d release_package
          cd release_package
          zip -r ../gedis-release.zip .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: gedis-release.zip
          name: gedis-${{ github.ref_name }}.zip
