name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-godot-cpp:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x86_64
          - os: macos-latest
            platform: macos
            arch: universal
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
    name: Build godot-cpp for ${{ matrix.platform }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install SCons
        run: pip install scons

      - name: Cache godot-cpp
        id: cache-godotcpp
        uses: actions/cache@v4
        with:
          path: |
            godot-cpp/bin
            godot-cpp/gen
          key: godot-cpp-${{ runner.os }}-${{ hashFiles('godot-cpp/SConstruct', 'godot-cpp/gdextension/extension_api.json', 'godot-cpp/binding_generator.py') }}

      - name: Build godot-cpp
        if: steps.cache-godotcpp.outputs.cache-hit != 'true'
        run: |
          cd godot-cpp
          scons platform=${{ matrix.platform }} arch=${{ matrix.arch }} generate_bindings=yes target=template_release
          scons platform=${{ matrix.platform }} arch=${{ matrix.arch }} target=template_debug

      - name: Upload godot-cpp artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godot-cpp-build-${{ matrix.platform }}
          path: |
            godot-cpp/bin
            godot-cpp/gen

  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x86_64
            artifact_name: gedis-windows-x86_64
          - os: macos-latest
            platform: macos
            arch: universal
            artifact_name: gedis-macos-universal
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
            artifact_name: gedis-linux-x86_64
    name: Build for ${{ matrix.platform }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    needs: build-godot-cpp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Download godot-cpp
        uses: actions/download-artifact@v4
        with:
          name: godot-cpp-build-${{ matrix.platform }}
          path: godot-cpp/

      - name: Set up build environment
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential scons
          elif [ "${{ runner.os }}" == "macOS" ]; then
            pip install scons
          fi
        shell: bash

      - name: Set up Windows build environment
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-pkg-config mingw-w64-x86_64-python mingw-w64-x86_64-python-pip make

      - name: Install SCons (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          python -m pip install --upgrade pip
          pip install scons

      - name: Build project (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          export PATH="/mingw64/bin:$PATH"
          
          # Set full paths to compilers (similar to build_local.sh approach)
          export CC=/mingw64/bin/x86_64-w64-mingw32-gcc
          export CXX=/mingw64/bin/x86_64-w64-mingw32-g++
          
          # Debug: Show environment and compiler availability
          echo "PATH: $PATH"
          echo "CC: $CC"
          echo "CXX: $CXX"
          echo "CC exists: $(test -f $CC && echo 'yes' || echo 'no')"
          echo "CXX exists: $(test -f $CXX && echo 'yes' || echo 'no')"
          which x86_64-w64-mingw32-gcc || echo "gcc not found in PATH"
          which x86_64-w64-mingw32-g++ || echo "g++ not found in PATH"
          x86_64-w64-mingw32-g++ --version
          
          # Show SCons version and Python version
          python --version
          scons --version
          
          # Build with verbose output to see what SCons is doing
          scons platform=windows target=template_release arch=${{ matrix.arch }} use_mingw=yes -j1 --debug=explain -v

      - name: Build project (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          scons platform=${{ matrix.platform }} target=template_release arch=${{ matrix.arch }}

      - name: Package addon
        shell: bash
        run: |
          mkdir -p package/addons/Gedis/bin
          cp -r addons/Gedis/* package/addons/Gedis/

          # Copy the built library
          if [ "${{ runner.os }}" == "Windows" ]; then
            cp addons/Gedis/bin/libgedis.dll package/addons/Gedis/bin/
          elif [ "${{ runner.os }}" == "macOS" ]; then
            cp addons/Gedis/bin/libgedis.dylib package/addons/Gedis/bin/
          else
            cp addons/Gedis/bin/libgedis.so package/addons/Gedis/bin/
          fi

          cd package
          zip -r ../${{ matrix.artifact_name }}.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}.zip

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Combine builds
        run: |
          mkdir -p release_package
          unzip artifacts/gedis-windows-x86_64.zip -d release_package
          unzip artifacts/gedis-macos-universal.zip -d temp_macos
          unzip artifacts/gedis-linux-x86_64.zip -d temp_linux
          cp -r temp_macos/addons/Gedis/bin/* release_package/addons/Gedis/bin/
          cp -r temp_linux/addons/Gedis/bin/* release_package/addons/Gedis/bin/
          cd release_package
          zip -r ../gedis-release.zip .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: gedis-release.zip
          name: gedis-${{ github.ref_name }}.zip
