name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux-and-windows:
    name: Build for Linux and Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install SCons and MinGW
        run: |
          pip install scons
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Cache godot-cpp for Linux
        id: cache-godotcpp-linux
        uses: actions/cache@v4
        with:
          path: |
            godot-cpp/bin
            godot-cpp/gen
          key: godot-cpp-linux-${{ hashFiles('godot-cpp/SConstruct', 'godot-cpp/gdextension/extension_api.json', 'godot-cpp/binding_generator.py') }}

      - name: Build godot-cpp for Linux
        if: steps.cache-godotcpp-linux.outputs.cache-hit != 'true'
        run: |
          cd godot-cpp
          scons platform=linux arch=x86_64 generate_bindings=yes target=template_release
          scons platform=linux arch=x86_64 target=template_debug

      - name: Build project for Linux
        run: |
          scons platform=linux target=template_release arch=x86_64
      
      - name: Package Linux addon
        run: |
          mkdir -p package-linux/addons/Gedis/bin
          cp -r addons/Gedis/* package-linux/addons/Gedis/
          cp addons/Gedis/bin/libgedis.so package-linux/addons/Gedis/bin/
          cd package-linux
          zip -r ../gedis-linux-x86_64.zip .
          cd ..

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: gedis-linux-x86_64
          path: gedis-linux-x86_64.zip

      - name: Cache godot-cpp for Windows
        id: cache-godotcpp-windows
        uses: actions/cache@v4
        with:
          path: |
            godot-cpp/bin
            godot-cpp/gen
          key: godot-cpp-windows-${{ hashFiles('godot-cpp/SConstruct', 'godot-cpp/gdextension/extension_api.json', 'godot-cpp/binding_generator.py') }}

      - name: Build godot-cpp for Windows
        if: steps.cache-godotcpp-windows.outputs.cache-hit != 'true'
        run: |
          cd godot-cpp
          export CC=/usr/bin/x86_64-w64-mingw32-gcc
          export CXX=/usr/bin/x86_64-w64-mingw32-g++
          scons platform=windows arch=x86_64 generate_bindings=yes target=template_release
          scons platform=windows arch=x86_64 target=template_debug

      - name: Build project for Windows
        run: |
          export CC=/usr/bin/x86_64-w64-mingw32-gcc
          export CXX=/usr/bin/x86_64-w64-mingw32-g++
          scons platform=windows use_mingw=yes target=template_release arch=x86_64

      - name: Package Windows addon
        run: |
          mkdir -p package-windows/addons/Gedis/bin
          cp -r addons/Gedis/* package-windows/addons/Gedis/
          cp addons/Gedis/bin/libgedis.dll package-windows/addons/Gedis/bin/
          cd package-windows
          zip -r ../gedis-windows-x86_64.zip .
          cd ..

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: gedis-windows-x86_64
          path: gedis-windows-x86_64.zip

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-linux-and-windows]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Combine builds
        run: |
          mkdir -p release_package
          unzip artifacts/gedis-linux-x86_64/gedis-linux-x86_64.zip -d release_package
          unzip artifacts/gedis-windows-x86_64/gedis-windows-x86_64.zip -d temp_windows
          cp -r temp_windows/addons/Gedis/bin/* release_package/addons/Gedis/bin/
          cd release_package
          zip -r ../gedis-release.zip .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: gedis-release.zip
          name: gedis-${{ github.ref_name }}.zip
